airbnb:
  phone_number:
  password:
server:
  ip: 0.0.0.0
  port: 22
  username: root
  private_key_path: /PATH/TO/KEY
  private_key_password: CAN_BE_LEFT_BLANK
mysql:
  host: 127.0.0.1
  username: root
  password: 123456
  database: airbnb
